// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYGKMjUlrxmBjvSPsosaBKf_SffweKZwk',
    appId: '1:557963828554:web:447071a3fe42c8cb7475b3',
    messagingSenderId: '557963828554',
    projectId: 'chat-app-a4dae',
    authDomain: 'chat-app-a4dae.firebaseapp.com',
    storageBucket: 'chat-app-a4dae.appspot.com',
    measurementId: 'G-LZBCQ63M9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCxodxjSybJhCc1CxP68OWVcdLLBWeI-c',
    appId: '1:557963828554:android:baaa24344a525f157475b3',
    messagingSenderId: '557963828554',
    projectId: 'chat-app-a4dae',
    storageBucket: 'chat-app-a4dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9sqshRymkSlhKTY4vgbqH26mtm5GPaKE',
    appId: '1:557963828554:ios:58411b4cb933704e7475b3',
    messagingSenderId: '557963828554',
    projectId: 'chat-app-a4dae',
    storageBucket: 'chat-app-a4dae.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9sqshRymkSlhKTY4vgbqH26mtm5GPaKE',
    appId: '1:557963828554:ios:5b2c9993de8064987475b3',
    messagingSenderId: '557963828554',
    projectId: 'chat-app-a4dae',
    storageBucket: 'chat-app-a4dae.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
